# https://golangci-lint.run/usage/configuration/#config-file
version: "2"

linters:
  enable:
    - decorder
    - dupl
    - errcheck
    - exhaustive
    - goconst
    - gosec
    - govet
    - ineffassign
    - misspell
    - mnd
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - predeclared
    - reassign
    - recvcheck
    - revive
    - staticcheck
    - tagalign
    - tagliatelle
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl_v5
  exclusions:
    generated: lax # Do not lint generated files.
    paths:
      - _test\.go # Do not lint test files.

  settings:
    dupl:
      threshold: 100 # Increase the threshold to 100 to avoid false positives.
    gosec:
      severity: "medium"
      confidence: "medium"
      excludes: []
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    mnd:
      ignored-numbers:
        - "0"
        - "1"
        - "100"
    revive:
      enable-all-rules: true
      severity: error # We want it to be blocking from now on.
      rules:
        - name: add-constant
          disabled: true
          arguments:
            # Do not force to use constants for zero values.
            - allow-floats: "0.0,0."
              allow-ints: "0"
              allow-strs: '""'
        - name: cyclomatic
          arguments:
            - 10 # Default value (4) is too low.
        - name: enforce-map-style
          arguments:
            - literal # Use `a := map[X]Y{}` (instead of `a := make(map[X]Y, ...)`).
        - name: enforce-slice-style
          arguments:
            - literal # Use `a := []X{}` (instead of `a := make([]X, ...)`).
        - name: use-errors-new
          disabled: true # Always use `fmt.Errorf`.
        - name: exported
          disabled: true # Need to add documentation to all exported functions, interface, types and so on...
        - name: line-length-limit
          arguments:
            - 120 # Change the default value from 80 to 120 for maximum line length.
        - name: package-comments
          disabled: true # Do not enforce package comments.
        - name: receiver-naming
          disabled: true # Do not enforce receiver naming.
        - name: unhandled-error
          disabled: true #We use `errcheck` for that.
        - name: cognitive-complexity
          arguments:
            - 10 # Increase the threshold to 10 to avoid false positives.
    staticcheck:
      checks:
        # Do not force to write `foo.Baz` if the developer explicitely want to write `foo.Bar.Baz` where `Bar` is an
        # embedded field (reference: https://staticcheck.dev/docs/checks/#QF1008)
        - -QF1008

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax # Do not format generated files.

issues:
  fix: true # Automatically fix issues.
  new-from-merge-base: master # Add new issues but do not try to fix all existing ones.
